# Generated by Django 5.1.2 on 2024-11-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("cines", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Prediccion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("pelicula", models.CharField(max_length=200)),
                ("fecha_prediccion", models.DateTimeField(auto_now_add=True)),
                ("exito_probable", models.FloatField()),
                (
                    "cine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="predicciones",
                        to="cines.cine",
                    ),
                ),
            ],
        ),
    ]
