# Generated by Django 5.1.2 on 2024-11-03 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("usuarios_cine", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Cine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("direccion", models.CharField(max_length=200)),
                ("capacidad", models.IntegerField()),
                (
                    "propietario",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cines",
                        to="usuarios_cine.usuario",
                    ),
                ),
            ],
        ),
    ]
