# Generated by Django 5.1.2 on 2024-11-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cines", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cine",
            name="propietario",
        ),
    ]
