# Generated by Django 5.1.2 on 2024-11-13 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cines", "0002_remove_cine_propietario"),
        ("predicciones", "0002_delete_prediccion"),
    ]

    operations = [
        migrations.CreateModel(
            name="Pelicula",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=100)),
                ("genero", models.CharField(max_length=30)),
                ("clasificación", models.CharField(max_length=10)),
                (
                    "imagen",
                    models.ImageField(
                        blank=True, null=True, upload_to="imagenes_peliculas/"
                    ),
                ),
            ],
        ),
        migrations.DeleteModel(
            name="Cine",
        ),
    ]
