# Generated by Django 5.1.2 on 2024-11-05 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios_cine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usuario",
            name="apellido_materno",
            field=models.CharField(default="N/A", max_length=40),
        ),
        migrations.AddField(
            model_name="usuario",
            name="apellido_paterno",
            field=models.CharField(default="N/A", max_length=40),
        ),
    ]
