# Generated by Django 5.1.2 on 2024-11-06 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("cines", "0002_remove_cine_propietario"),
        ("usuarios_cine", "0002_usuario_apellido_materno_usuario_apellido_paterno"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Usuario",
        ),
    ]
